### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by jhibbeard89** [jhibbeard89/git-workshop#11]
# Feature Request

## **Feature description**

This is the initial navbar, that will allow the user to navigate to key areas of the website, such as sign in, sign up and other primary navigation needs. 

### **Feature experience**

- As a `visitor` I can navigate to sign in
- As a `visitor` I can navigate to sign up 
- As a `user` I can navigate to primary pages in the website. 

### **Todo**

- [ ] Add Sign in link
- [ ] Add a Sign up link
- [ ] Add links for users to access required signed-in pages. 

### **Potential Challenges**

- This should be dynamic and adapt to a user's status be they signed in or not. Using methods to check for this can make the header dynamic.
